//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MB.AgilePortfolio.PL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProject
    {
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public string Filepath { get; set; }
        public System.Guid PrivacyId { get; set; }
        public string Image { get; set; }
        public string Description { get; set; }
        public System.Guid UserId { get; set; }
        public System.DateTime DateCreated { get; set; }
        public string Purpose { get; set; }
        public string Environment { get; set; }
        public string Challenges { get; set; }
        public string FuturePlans { get; set; }
        public string Collaborators { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string SoftwareUsed { get; set; }
        public System.Guid StatusId { get; set; }
    }
}
