BEGIN
	INSERT INTO [dbo].tblLanguage(Id, [Description])
		VALUES 
		(NEWID(), 'Java'),
		(NEWID(), 'C'),
		(NEWID(), 'Python'),
		(NEWID(), 'C++'),
		(NEWID(), 'Visual Basic'),
		(NEWID(), 'C#'),
		(NEWID(), 'PHP'),
		(NEWID(), 'HTML'),
		(NEWID(), 'JavaScript'),
		(NEWID(), 'SQL'),
		(NEWID(), 'Objective-C'),
		(NEWID(), 'Ruby'),
		(NEWID(), 'MATLAB'),
		(NEWID(), 'Assembly'),
		(NEWID(), 'Swift'),
		(NEWID(), 'Go'),
		(NEWID(), 'Perl'),
		(NEWID(), 'R'),
		(NEWID(), 'PL/SQL'),
		(NEWID(), 'SAS'),
		(NEWID(), 'F#'),
		(NEWID(), 'COBOL'),
		(NEWID(), 'Scala'),
		(NEWID(), 'ABAP'),
		(NEWID(), 'Fortran'),
		(NEWID(), 'Rust'),
		(NEWID(), 'Prolog'),
		(NEWID(), 'Ada'),
		(NEWID(), 'Pascal'),
		(NEWID(), 'Haskell'),
		(NEWID(), 'Apex'),
		(NEWID(), 'Kotlin'),
		(NEWID(), 'Bash'),
		(NEWID(), 'Clojure'),
		(NEWID(), 'Scheme'),
		(NEWID(), 'TypeScript'),
		(NEWID(), 'Erlang'),
		(NEWID(), 'CSS')
END